Repository Neovici/cosmoz-autocomplete, pull requests merged in 2020-04, with the labels that each got.

#30 cosmoz-autocomplete v2
  .codeclimate.yml
  .editorconfig
  .eslintignore
  .eslintrc
  .eslintrc.json
  .github/karma-problem-matcher.json
  .github/workflows/workflow.yml
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  .travis.yml
  CONTRIBUTING.md
  LICENSE.md
  README.md
  bower.json
  cosmoz-autocomplete.html
  cosmoz-autocomplete.js
  cosmoz-suggestions.js
  custom-elements.json
  demo/index.html
  demo/items.json
  es-dev-server.config.js
  gulpfile.js
  index.html
  karma.conf.js
  lib/use-autocomplete.js
  lib/use-keyboard.js
  lib/use-suggestions.js
  lib/utils.js
  package-lock.json
  package.json
  polymer.json
  shell.nix
  stories/cosmoz-autocomplete.stories.js
  test/.eslintrc
  test/.eslintrc.json
  test/cosmoz-autocomplete_test.html
  test/cosmoz-suggestions.test.js
  test/index.html
  test/use-keyboard.test.js
  test/use-suggestions.test.js
  wct.conf.json
  yarn.lock
Labels: enhancement

#35 Update CC test reporter ID
  .github/workflows/ci.yml
Labels: bug

#36 Fixes multiple text state updates on clear
  cosmoz-autocomplete.js
  lib/use-autocomplete.js
  package-lock.json
  stories/cosmoz-autocomplete.stories.js
Labels: bug, enhancement

#39 Implement chips
  .codeclimate.yml
  cosmoz-autocomplete.js
  cosmoz-suggestions.js
  lib/autocomplete.js
  lib/use-autocomplete.js
  lib/use-input.js
  lib/use-keyboard.js
  lib/use-select.js
  lib/utils.js
  stories/cosmoz-autocomplete.stories.js
  stories/data.js
  test/cosmoz-suggestions.test.js
  test/utils.test.js
Labels: enhancement

#41 fix: unarray value on select if limit is 1
  lib/use-select.js
Labels: enhancement

#43 fix: adds suggestionsWidth property
  cosmoz-suggestions.js
  lib/autocomplete.js
Labels: enhancement
